### ISSUE TITLE
Display WebSocket error messages

### ISSUE THREAD

**Issue by Rybadour** [j3d42/coc-godot#1]
I trying to get this setup today and it didn't seem to be working. Even when I opened the logs coming from this extension I was confused as it kept printing "connecting" then "disconnected". Which made me realize it probably just had an error as you tell errors to just disconnect without printing the error. Realized that if it's a socket layer issue maybe it's a port conflict. I was lucky but it would have helped to see a clear error message!

Btw: Thank you for this awesome plugin!

**Comment by chaource** [comment]
Sorry for the late reply, I believe this extension is now useless since https://github.com/godotengine/godot/issues/34523 was closed in `3.2.2` ! So I won't be updating this extension anymore.
